backend:
  name: github
  repo: confitalk/confitalk-website
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tytuł (PL)", name: "title_pl", widget: "string"}
      - {label: "Title (EN)", name: "title_en", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Treść (PL)", name: "body_pl", widget: "markdown"}
      - {label: "Content (EN)", name: "body_en", widget: "markdown"}
